require:
  - 'rubocop-rspec'

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Layout/LineLength:
  Enabled: false
Lint/UriEscapeUnescape:
  Enabled: false
Metrics/AbcSize:
  Exclude:
    - 'Rakefile'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/MethodLength:
  Exclude:
    - 'Rakefile'
Naming/FileName:
  Exclude:
    - 'spec/open_spf/**/*'
Naming/MethodParameterName:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Max: 12
RSpec/StubbedMock:
  Enabled: false
RSpec/SubjectStub:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/SymbolArray:
  Exclude:
    - 'spec/open_spf/**/*'
